-- MySQL Script generated by MySQL Workbench
-- Tue May 21 16:23:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema create_opdracht
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema create_opdracht
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `create_opdracht` DEFAULT CHARACTER SET utf8 ;
USE `create_opdracht` ;

-- -----------------------------------------------------
-- Table `create_opdracht`.`classification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`classification` (
  `key` INT(11) NOT NULL,
  `classification` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `classification_UNIQUE` (`classification` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`hair_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`hair_color` (
  `key` INT(11) NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `color_UNIQUE` (`color` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`gender` (
  `key` INT(11) NOT NULL,
  `gender` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `gender_UNIQUE` (`gender` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`people` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `height` INT(11) NULL DEFAULT NULL,
  `mass` INT(11) NULL DEFAULT NULL,
  `birth_year` INT(11) NULL DEFAULT NULL,
  `gender` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_people_gender_idx` (`gender` ASC),
  CONSTRAINT `FK_people_gender`
    FOREIGN KEY (`gender`)
    REFERENCES `create_opdracht`.`gender` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`ct_people_hair_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`ct_people_hair_color` (
  `person` INT(11) NOT NULL,
  `color` INT(11) NOT NULL,
  PRIMARY KEY (`person`, `color`),
  INDEX `FK_hair_color_people_idx` (`color` ASC),
  CONSTRAINT `FK_hair_color_people`
    FOREIGN KEY (`color`)
    REFERENCES `create_opdracht`.`hair_color` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_people_hair_color`
    FOREIGN KEY (`person`)
    REFERENCES `create_opdracht`.`people` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`skin_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`skin_color` (
  `key` INT(11) NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `color_UNIQUE` (`color` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`ct_people_skin_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`ct_people_skin_color` (
  `person` INT(11) NOT NULL,
  `color` INT(11) NOT NULL,
  PRIMARY KEY (`person`, `color`),
  INDEX `FK_skin_color_people_idx` (`color` ASC),
  CONSTRAINT `FK_people_skin_color`
    FOREIGN KEY (`person`)
    REFERENCES `create_opdracht`.`people` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_skin_color_people`
    FOREIGN KEY (`color`)
    REFERENCES `create_opdracht`.`skin_color` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`designation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`designation` (
  `key` INT(11) NOT NULL,
  `designation` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `designation_UNIQUE` (`designation` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`species` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `classification` INT(11) NOT NULL,
  `designation` INT(11) NOT NULL,
  `average_height` INT(11) NULL DEFAULT NULL,
  `average_lifespan` INT(11) NULL DEFAULT NULL,
  `language` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_classification_idx` (`classification` ASC),
  INDEX `FK_species_designation_idx` (`designation` ASC),
  CONSTRAINT `FK_species_classification`
    FOREIGN KEY (`classification`)
    REFERENCES `create_opdracht`.`classification` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_species_designation`
    FOREIGN KEY (`designation`)
    REFERENCES `create_opdracht`.`designation` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`eye_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`eye_color` (
  `key` INT(11) NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `color_UNIQUE` (`color` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`ct_species_eye_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`ct_species_eye_color` (
  `species` INT(11) NOT NULL,
  `color` INT(11) NOT NULL,
  PRIMARY KEY (`species`, `color`),
  INDEX `FK_species_eye_color_idx` (`color` ASC),
  CONSTRAINT `FK_eye_color_species`
    FOREIGN KEY (`species`)
    REFERENCES `create_opdracht`.`species` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_species_eye_color`
    FOREIGN KEY (`color`)
    REFERENCES `create_opdracht`.`eye_color` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`ct_species_hair_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`ct_species_hair_color` (
  `species` INT(11) NOT NULL,
  `color` INT(11) NOT NULL,
  PRIMARY KEY (`species`, `color`),
  INDEX `FK_species_hair_color_idx` (`color` ASC),
  CONSTRAINT `FK_hair_color_species`
    FOREIGN KEY (`species`)
    REFERENCES `create_opdracht`.`species` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_species_hair_color`
    FOREIGN KEY (`color`)
    REFERENCES `create_opdracht`.`hair_color` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `create_opdracht`.`ct_species_skin_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `create_opdracht`.`ct_species_skin_color` (
  `species` INT(11) NOT NULL,
  `color` INT(11) NOT NULL,
  INDEX `FK_skin_color_species_idx` (`species` ASC),
  INDEX `FK_species_skin_color` (`color` ASC),
  PRIMARY KEY (`color`, `species`),
  CONSTRAINT `FK_skin_color_species`
    FOREIGN KEY (`species`)
    REFERENCES `create_opdracht`.`species` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_species_skin_color`
    FOREIGN KEY (`color`)
    REFERENCES `create_opdracht`.`skin_color` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `create_opdracht`.`classification`
-- -----------------------------------------------------
START TRANSACTION;
USE `create_opdracht`;
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (4, 'amphibian');
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (9, 'artificial');
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (1, 'gastropod');
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (7, 'insectoid');
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (2, 'mammal');
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (6, 'mammals');
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (3, 'reptile');
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (8, 'reptilian');
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (0, 'sentient');
INSERT INTO `create_opdracht`.`classification` (`key`, `classification`) VALUES (5, 'unknown');

COMMIT;


-- -----------------------------------------------------
-- Data for table `create_opdracht`.`hair_color`
-- -----------------------------------------------------
START TRANSACTION;
USE `create_opdracht`;
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (11, 'auburn');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (5, 'black');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (7, 'blond');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (9, 'blonde');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (2, 'brown');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (10, 'grey');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (0, 'hair_colors');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (1, 'n/a');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (4, 'none');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (6, 'red');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (8, 'unknown');
INSERT INTO `create_opdracht`.`hair_color` (`key`, `color`) VALUES (3, 'white');

COMMIT;


-- -----------------------------------------------------
-- Data for table `create_opdracht`.`gender`
-- -----------------------------------------------------
START TRANSACTION;
USE `create_opdracht`;
INSERT INTO `create_opdracht`.`gender` (`key`, `gender`) VALUES (2, 'female');
INSERT INTO `create_opdracht`.`gender` (`key`, `gender`) VALUES (3, 'hermaphrodite');
INSERT INTO `create_opdracht`.`gender` (`key`, `gender`) VALUES (0, 'male');
INSERT INTO `create_opdracht`.`gender` (`key`, `gender`) VALUES (1, 'n/a');
INSERT INTO `create_opdracht`.`gender` (`key`, `gender`) VALUES (4, 'none');

COMMIT;


-- -----------------------------------------------------
-- Data for table `create_opdracht`.`skin_color`
-- -----------------------------------------------------
START TRANSACTION;
USE `create_opdracht`;
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (30, 'asian');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (29, 'black');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (3, 'blue');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (9, 'brown');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (13, 'brown mottle');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (28, 'caucasian');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (12, 'dark');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (0, 'fair');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (1, 'gold');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (24, 'gray');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (7, 'green');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (8, 'green-tan');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (14, 'grey');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (31, 'hispanic');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (4, 'light');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (21, 'magenta');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (11, 'metal');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (15, 'mottled green');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (27, 'n/a');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (20, 'none');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (16, 'orange');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (10, 'pale');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (25, 'pale pink');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (26, 'peach');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (23, 'pink');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (22, 'purple');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (5, 'red');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (19, 'silver');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (18, 'tan');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (6, 'unknown');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (2, 'white');
INSERT INTO `create_opdracht`.`skin_color` (`key`, `color`) VALUES (17, 'yellow');

COMMIT;


-- -----------------------------------------------------
-- Data for table `create_opdracht`.`designation`
-- -----------------------------------------------------
START TRANSACTION;
USE `create_opdracht`;
INSERT INTO `create_opdracht`.`designation` (`key`, `designation`) VALUES (1, 'reptilian');
INSERT INTO `create_opdracht`.`designation` (`key`, `designation`) VALUES (0, 'sentient');

COMMIT;


-- -----------------------------------------------------
-- Data for table `create_opdracht`.`eye_color`
-- -----------------------------------------------------
START TRANSACTION;
USE `create_opdracht`;
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (0, 'amber');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (6, 'black');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (8, 'blue');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (3, 'brown');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (13, 'golden');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (4, 'green');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (15, 'grey');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (10, 'hazel');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (11, 'indigo');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (14, 'n/a');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (5, 'orange');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (7, 'pink');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (2, 'red');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (12, 'silver');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (9, 'unknown');
INSERT INTO `create_opdracht`.`eye_color` (`key`, `color`) VALUES (1, 'yellow');

COMMIT;